#SetParameterVariable
from pyomo.environ import *

class SetParameterVariableModel:
    """SetParameterVariable."""

    def __init__(self, model):
        """Attach SetParameterVariable to an existing model."""
        self.model = model
        
        # =============================
        # DEFINE SETS
        # =============================
        model.Macronutrients = Set()
        model.Components = Set()
        model.Products = Set()
        model.Milling = Set()
        model.FWManagementOption = Set()
        model.GlucoseUpgrading = Set()
        model.NonGlucoseUpgrading=Set()
        model.CarbonCapture = Set()
        model.Equipment = Set()
        model.Chemicals = Set()
        model.Utility = Set()
        model.Emissions = Set()
        model.SocialImpact = Set()

        # =============================
        # DEFINE PARAMETERS
        # =============================
        model.FWsupply_availability = Param (domain=NonNegativeReals, mutable=True) 
        model.FWMacronutrient = Param(model.Macronutrients, within=NonNegativeReals, mutable=True)
        model.CapacityFWManagement = Param(model.FWManagementOption, within=NonNegativeReals)
        #Technical score
        model.TechnicalScore = Param(model.FWManagementOption, within=NonNegativeReals)
        model.MaxTechnicalScore = Param(within=NonNegativeReals)
        #Chemical consumption 
        model.ChemicalPretreatmentConsumption = Param(model.Chemicals, model.FWManagementOption, model.Equipment, within=NonNegativeReals)
        model.ChemicalGlucoseUpgradingConsumption = Param(model.Chemicals, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.ChemicalConsumptionNonFermentation = Param(model.Components, model.NonGlucoseUpgrading, within=NonNegativeReals)
        model.ChemicalConsumptionComposting = Param(model.Components, model.FWManagementOption, within=NonNegativeReals)
        #Pretreatment 
        model.MolecularWeight = Param(model.Components, within=NonNegativeReals) 
        model.StoichiometricCoeff = Param(model.Components) 
        model.ConversionFactor = Param( within=NonNegativeReals) 
        #Bioethanol
        model.MolecularWeightFermenter1 = Param(model.Components, within=NonNegativeReals)
        model.StoichiometricCoeffFermenter1 = Param(model.Components)
        model.ConversionFactorFermenter1 = Param(within=NonNegativeReals)
        model.RecoveryTopDT1 = Param(model.Components, within=NonNegativeReals)
        model.RecoveryTopDT2 = Param(model.Components, within=NonNegativeReals)
        model.RecoveryProductMS = Param(model.Components, within=NonNegativeReals)
        #Lactic Acid
        model.SolventConsumptionLactic = Param (model.Components, model.GlucoseUpgrading, within=NonNegativeReals)
        model.MolecularWeightFermenter4 = Param(model.Components, within=NonNegativeReals)
        model.StoichiometricCoeffFermenter4 = Param(model.Components)
        model.ConversionFactorFermenter4 = Param(within=NonNegativeReals)
        model.MolecularWeightReactor1 = Param(model.Components, within=NonNegativeReals)
        model.StoichiometricCoeffReactor1  = Param(model.Components)
        model.ConversionFactorReactor1  = Param(within=NonNegativeReals)
        model.MolecularWeightReactor2 = Param(model.Components, within=NonNegativeReals)
        model.StoichiometricCoeffReactor2  = Param(model.Components)
        model.ConversionFactorReactor2  = Param(within=NonNegativeReals)
        model.MethanolRatio = Param(within=NonNegativeReals)
        model.WaterRatio  = Param(within=NonNegativeReals)
        model.RecoveryTopDT8  = Param(model.Components, within=NonNegativeReals)
        model.RecoveryBottomDT9 = Param(model.Components, within=NonNegativeReals)
        model.RecoveryTopDT10 = Param(model.Components, within=NonNegativeReals)
        model.RecoveryTopDT11 = Param(model.Components, within=NonNegativeReals)
        model.RecoveryTopDT12 = Param(model.Components, within=NonNegativeReals)
        model.RecoveryTopDT13 = Param(model.Components, within=NonNegativeReals)
        #BDO
        model.AirConsumptionBDO = Param(model.Components,model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.MolecularWeightFermenter2 = Param(model.Components)
        model.StoichiometricCoeffFermenter2 = Param(model.Components)
        model.ConversionFactorFermenter2 = Param(within=NonNegativeReals)
        model.TopFlashdrum2  = Param(model.Components, within=NonNegativeReals)
        model.TopliquidDT3 = Param(model.Components, within=NonNegativeReals)
        model.TopgasDT3 = Param(model.Components, within=NonNegativeReals)
        model.TopFlashdrum3  = Param(model.Components, within=NonNegativeReals)
        #Succinic Acid 
        model.CO2ConsumptionSA = Param(within=NonNegativeReals)
        model.MolecularWeightFermenter5 = Param(model.Components, within=NonNegativeReals)
        model.StoichiometricCoeffFermenter5 = Param(model.Components)
        model.ConversionFactorFermenter5 = Param(within=NonNegativeReals)
        model.TopEvaporator = Param(model.Components,within=NonNegativeReals)
        #Butanol
        model.MolecularWeightButanol = Param (model.Components, within=NonNegativeReals)
        model.StoichiometricCoeffButanol1 = Param(model.Components, within=Reals)
        model.StoichiometricCoeffButanol2 = Param (model.Components, within=Reals)
        model.StoichiometricCoeffButanol3 = Param (model.Components, within=Reals)
        model.StoichiometricCoeffButanol4 = Param (model.Components, within=Reals)
        model.StoichiometricCoeffButanol5 = Param (model.Components, within=Reals)
        model.ConversionFactorButanol1 = Param(within=NonNegativeReals)
        model.ConversionFactorButanol2 = Param(within=NonNegativeReals)
        model.ConversionFactorButanol3 = Param(within=NonNegativeReals)
        model.ConversionFactorButanol4 = Param(within=NonNegativeReals)
        model.ConversionFactorButanol5 = Param(within=NonNegativeReals)
        model.TopDT4 = Param(model.Components)
        model.TopDT5 = Param(model.Components)
        model.TopDT6= Param(model.Components)
        model.BottomDecant1 = Param(model.Components)
        model.BottomDT7= Param(model.Components)
        #Biodiesel
        model.MolecularWeightTranesterReactor = Param(model.Components, within=NonNegativeReals)
        model.StoichiometricCoeffTranesterReactor = Param(model.Components)
        model.ConversionFactorTranesterReactor = Param(within=NonNegativeReals)
        model.RecoveryTopDT14 = Param(model.Components, within=NonNegativeReals)
        model.RecoveryBiodieselProduct = Param(model.Components, within=NonNegativeReals)
        model.RecoveryTopDT16 = Param(model.Components, within=NonNegativeReals)
        model.RecoveryTopWasher = Param(model.Components, within=NonNegativeReals)
        model.H3PO4Consumption = Param(within=NonNegativeReals)
        model.MolecularWeightNeutralizer = Param(model.Components, within=NonNegativeReals)
        model.StoichiometricCoeffNeutralizer = Param(model.Components)
        model.ConversionFactorNeutralizer = Param(within=NonNegativeReals)
        #Protein extraction 
        model.RecoveryFiltration = Param (model.Components, within=NonNegativeReals)
        #Composting
        model.CompostYield = Param (model.Products, within=NonNegativeReals)
        model.EmissionComposting = Param (model.Emissions, model.FWManagementOption,  within=NonNegativeReals)
        #Incineration 
        model.StoichiometricO2 = Param (model.Components, within=NonNegativeReals)
        model.ExcessAirRatio = Param (within=NonNegativeReals)
        model.MolecularWeightBurner = Param(model.Components, within=NonNegativeReals)
        model.StoichiometricCoeffReaction1 = Param(model.Components, within=Reals)
        model.StoichiometricCoeffReaction2 = Param(model.Components, within=Reals)
        model.StoichiometricCoeffReaction3 = Param(model.Components, within=Reals)
        model.ConversionFactorBurner = Param(model.Components, within=NonNegativeReals)
        model.LHVFW = Param (within=NonNegativeReals)
        model.LHVSolidWaste = Param (within=NonNegativeReals)
        model.EffBoiler = Param (within=NonNegativeReals)
        model.EffComb = Param (within=NonNegativeReals)
        model.EffTurbine = Param (within=NonNegativeReals)
        model.SpecificEnthalpySteam = Param (within=NonNegativeReals)
        model.SpecificEnthalpyWater = Param (within=NonNegativeReals)
        #Anaerobic digestion
        model.MolecularWeightDigester = Param(model.Components, within=NonNegativeReals)
        model.StoichiometricCoeffDigester1 = Param(model.Components, within=Reals)
        model.StoichiometricCoeffDigester2 = Param(model.Components, within=Reals)
        model.StoichiometricCoeffDigester3 = Param(model.Components, within=Reals)
        model.StoichiometricCoeffDigester4 = Param(model.Components, within=Reals)
        model.ConversionFactorDigester  = Param(model.Components, within=NonNegativeReals)
        model.Recoverymembrane1 = Param(model.Components,within=NonNegativeReals)
        model.Recoverymembrane2  = Param(model.Components,within=NonNegativeReals)
        #Carbon capture
        model.SolventCCU = Param(model.Components,within=NonNegativeReals)
        model.RecoveryTopAbsorber2 = Param(model.Components,within=NonNegativeReals)
        model.TopDT18 = Param(model.Components,within=NonNegativeReals)
        #Product revenue
        model.ProductDemand = Param(model.Products, within=NonNegativeReals)
        model.ProductSellingPrice = Param(model.Products, within=NonNegativeReals)
        #Capital investment 
        model.equipment_installation = Param(within=NonNegativeReals) 
        model.instrumentation_control_system= Param(within=NonNegativeReals) 
        model.process_piping = Param(within=NonNegativeReals) 
        model.electrical_equipment = Param(within=NonNegativeReals) 
        model.buildings=Param(within=NonNegativeReals) 
        model.site_development=Param(within=NonNegativeReals) 
        model.auxiliary_facilities=Param(within=NonNegativeReals) 
        model.engineering=Param(within=NonNegativeReals) 
        model.construction=Param(within=NonNegativeReals) 
        model.constractor_fee=Param(within=NonNegativeReals) 
        model.contingency=Param(within=NonNegativeReals) 
        model.working_capital=Param(within=NonNegativeReals) 
        model.land_use=Param(within=NonNegativeReals) 
        model.Base_equipment_cost= Param(  model.Equipment,within=NonNegativeReals)
        model.Base_reference_mass= Param( model.Equipment, within=NonNegativeReals)
        model.sizing_factor= Param(model.Equipment, within=NonNegativeReals)
        #Operational 
        model.Utility_price = Param(model.Utility,within=NonNegativeReals)
        model.FWPrice = Param(within=NonNegativeReals)
        model.raw_material_price = Param(model.Chemicals, within=NonNegativeReals)
        model.chemical_fermentation_Price = Param (model.Chemicals,within=NonNegativeReals)
        model.chemical_nonfermentation_Price = Param(model.Components, within=NonNegativeReals)
        model.chemical_composting_Price = Param (model.Components,within=NonNegativeReals)
        #Economic factor 
        model.work_hour=Param()
        model.ConstructionYears = RangeSet(1, 3)  # Construction period of 3 years
        model.OperationalYears = RangeSet(4, 33)  # Operational period of 30 years
        model.DepreciationYears = RangeSet(4, 14)
        model.federal_tax_rate = Param(within=NonNegativeReals) 
        model.discount_rate = Param(within=NonNegativeReals) 
        model.macrs_percentage = Param(model.DepreciationYears, within=NonNegativeReals)
        #Life cycle assessment 
        model.GWPutility = Param(model.Utility, within=NonNegativeReals)
        model.GWPchemical = Param(model.Chemicals, within=NonNegativeReals)
        model.GWPchemicalNonFermentation = Param(model.Components, within=NonNegativeReals)
        model.GWPchemicalComposting = Param(model.Components, within=NonNegativeReals)
        model.GWPDirectEmission = Param(model.Emissions, within=NonNegativeReals)
        model.GWPProduct = Param (model.Products, within=NonNegativeReals)
        #Social impact assessment 
        model.JobGenerationMultiplier = Param(model.SocialImpact)
        
        # =============================
        # DEFINE VARIABLES
        # =============================
        model.FWsupply = Var(within=NonNegativeReals)
        model.Fmill_component = Var(model.Components, model.Milling, model.Equipment, within=NonNegativeReals)
        # Stages selection
        model.Finfeedstock = Var(model.FWManagementOption, within=NonNegativeReals)
        model.StageSelected = Var(model.FWManagementOption, domain=NonNegativeReals, bounds=(0, 1))
        model.Tavg = Var(model.FWManagementOption, within=NonNegativeReals)
        #Pretreatment
        model.Fpump1 = Var(model.Components, model.FWManagementOption, model.Equipment, within=NonNegativeReals)
        model.FPretreatment_component = Var(model.Components, model.FWManagementOption, model.Equipment, within=NonNegativeReals)
        model.InitialMoles = Var(model.Components,model.FWManagementOption, model.Equipment,  within=NonNegativeReals)
        model.MolesReacted = Var(model.Components,model.FWManagementOption, model.Equipment,  within=NonNegativeReals)
        model.FinalMoles = Var(model.Components,model.FWManagementOption, model.Equipment,  within=NonNegativeReals)
        model.FinalMass = Var(model.Components,model.FWManagementOption, model.Equipment,  within=NonNegativeReals)
        model.FCentrifugal1_liquid= Var (model.Components,model.FWManagementOption, model.Equipment, within=NonNegativeReals)
        model.FCentrifugal1_Solid = Var (model.Components,model.FWManagementOption, model.Equipment, within=NonNegativeReals)
        #Gloucose upgrading selection
        model.Finglucose_component = Var(model.Components, model.GlucoseUpgrading, within=NonNegativeReals)
        model.GlucoseSelected = Var(model.GlucoseUpgrading,  bounds=(0,1))
        #Bioethanol process
        model.FBioethanol1 = Var(model.Components,model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.InitialMolesFermenter1 = Var(model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.MolesReactedFermenter1 = Var(model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.FinalMolesFermenter1 = Var(model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.FinalMassFermenter1 = Var(model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.Fflashdrum1_liquid = Var(model.Components,model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.Fflashdrum1_gas = Var (model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.FBioethanol2 = Var(model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.FDT1_top = Var (model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.FDT1_bottom = Var (model.Components,model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.FDT2_top = Var (model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.FDT2_bottom = Var (model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.Fheater3 = Var(model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.FMS_bottom = Var (model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.BioethanolProduct = Var(model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.totalwaste_bioethanol = Var (model.Components, model.GlucoseUpgrading, within=NonNegativeReals)
        #Lactic Acid 
        model.FinLacticAcid1_component = Var (model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.InitialMolesFermenter4 = Var(model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.MolesReactedFermenter4 = Var(model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.FinalMolesFermenter4 = Var(model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.FinalMassFermenter4 = Var(model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.FoutDT8_top_component = Var(model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.FoutDT8_bottom_component = Var(model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.total_methanol_needed = Var (model.Components,  model.GlucoseUpgrading, within=NonNegativeReals)
        model.FinLacticAcid3_component = Var(model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.InitialMolesReactor1 = Var(model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.MolesReactedReactor1 = Var(model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.FinalMolesReactor1  = Var(model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.FinalMassReactor1  = Var(model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.FoutDT9_top_component = Var(model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.FoutDT9_bottom_component = Var(model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.FinDT10_component = Var(model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.FoutDT10_top_component = Var(model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.FoutDT10_bottom_component = Var(model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.Finpump9_component = Var(model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.FinLacticAcid4_component = Var(model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.InitialMolesReactor2 = Var(model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.MolesReactedReactor2 = Var(model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.FinalMolesReactor2  = Var(model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.FinalMassReactor2  = Var(model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.Finheater7_component = Var(model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.FinDT11_component = Var(model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.FoutDT11_top_component = Var(model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.FoutDT11_bottom_component = Var(model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.FinDT12_component = Var(model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.FoutDT12_top_component = Var(model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.FoutDT12_bottom_component = Var(model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.FinDT13_component = Var(model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.FoutDT13_top_component = Var(model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.LacticAcidProduct = Var(model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.water_recycle_Lactic = Var(model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.methanol_recycle_Lactic = Var(model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.Lactic_waste = Var (model.Components,model.GlucoseUpgrading, within=NonNegativeReals)
        #BDO
        model.Fincomp1 = Var(model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.FinBDO_component = Var(model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.InitialMolesFermenter2 = Var(model.Components,model.GlucoseUpgrading,model.Equipment, domain=NonNegativeReals)
        model.MolesReactedFermenter2 = Var(model.Components,model.GlucoseUpgrading, model.Equipment, domain=NonNegativeReals)
        model.FinalMolesFermenter2 = Var(model.Components, model.GlucoseUpgrading, model.Equipment, domain=NonNegativeReals)
        model.FinalMassFermenter2 = Var(model.Components, model.GlucoseUpgrading, model.Equipment, domain=NonNegativeReals)
        model.Foutflashdrum2_gas_component = Var (model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.Foutflashdrum2_liquid_component = Var (model.Components, model.GlucoseUpgrading, model.Equipment,within=NonNegativeReals)
        model.FoutDT3_top_gas_component = Var (model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.FoutDT3_top_liquid_component = Var (model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.BDO_product = Var (model.Components,model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.Foutflashdrum3_liquid_component = Var (model.Components, model.GlucoseUpgrading, model.Equipment,within=NonNegativeReals)
        model.Foutflashdrum3_gas_component = Var (model.Components,model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.CO2_stream_BDO = Var (model.Components,model.GlucoseUpgrading,  within=NonNegativeReals)
        model.totalwaste_BDO = Var (model.Components,model.GlucoseUpgrading, within=NonNegativeReals)
        #Succinic Acid 
        model.FinSuccinicAcid1_component = Var (model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.CO2_stream_Succinic = Var (model.Components, model.GlucoseUpgrading, within=NonNegativeReals)
        model.InitialMolesFermenter5 = Var(model.Components, model.GlucoseUpgrading, model.Equipment, domain=NonNegativeReals)
        model.MolesReactedFermenter5 = Var(model.Components, model.GlucoseUpgrading, model.Equipment, domain=NonNegativeReals)
        model.FinalMolesFermenter5 = Var(model.Components, model.GlucoseUpgrading, model.Equipment, domain=NonNegativeReals)
        model.FinalMassFermenter5 = Var(model.Components, model.GlucoseUpgrading, model.Equipment, domain=NonNegativeReals)
        model.FoutEvaporator2_top_component = Var (model.Components,model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.FoutEvaporator2_bottom_component = Var (model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.FinCentrifugal6_component = Var (model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.FoutCentrifugal6_liquid_component = Var (model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.SuccinicAcidProduct= Var (model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.Succinic_waste = Var (model.Components,model.GlucoseUpgrading, within=NonNegativeReals)
        #Butanol
        model.FinButanol_component = Var(model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.InitialMolesFermenter3 = Var(model.Components,model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.MolesReacted1Fermenter3 = Var(model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.MolesReacted2Fermenter3 = Var(model.Components,model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.MolesReacted3Fermenter3 = Var(model.Components,model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.MolesReacted4Fermenter3 = Var(model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.MolesReacted5Fermenter3 = Var(model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.FinalMolesFermenter3 = Var(model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.FinalMassFermenter3 =Var(model.Components,model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.Foutflashdrum4_liquid_component = Var (model.Components, model.GlucoseUpgrading, model.Equipment,  within=NonNegativeReals)
        model.Foutflashdrum4_gas_component = Var (model.Components, model.GlucoseUpgrading, model.Equipment,  within=NonNegativeReals)
        model.CO2_stream_Butanol = Var (model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.H2_coproduct = Var (model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.FoutDT4_top_component = Var (model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.FoutDT4_bottom_component = Var (model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.Acetone_coproduct = Var (model.Components,model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.FoutDT5_bottom_component = Var (model.Components,model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.Ethanol_coproduct = Var (model.Components,model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.FoutDT6_bottom_component = Var (model.Components,model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.FoutDecant1_top_component = Var (model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.FoutDecant1_bottom_component = Var (model.Components,model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.FoutDT7_top_component = Var (model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.Butanol_product = Var (model.Components, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.totalwaste_Butanol = Var (model.Components, model.GlucoseUpgrading, within=NonNegativeReals)
        #Biodiesel process 
        model.FHexane = Var (model.Components, model.NonGlucoseUpgrading,   within=NonNegativeReals)
        model.FBiodiesel1 = Var (model.Components, model.NonGlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.FCentrifugal2_Liquid = Var (model.Components, model.NonGlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.FCentrifugal2_Solid = Var (model.Components, model.NonGlucoseUpgrading, model.Equipment,within=NonNegativeReals)
        model.FEvaporator1_gas = Var (model.Components, model.NonGlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.FEvaporator1_liquid = Var (model.Components, model.NonGlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.ChemicalBiodieselStream= Var (model.Components, model.NonGlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.InitialMolesTranesterReactor= Var(model.Components, model.NonGlucoseUpgrading, model.Equipment, domain=NonNegativeReals)
        model.MolesReactedTranesterReactor = Var(model.Components, model.NonGlucoseUpgrading, model.Equipment, domain=NonNegativeReals)
        model.FinalMolesTranesterReactor = Var(model.Components, model.NonGlucoseUpgrading, model.Equipment, domain=NonNegativeReals)
        model.FinalMassTranesterReactor = Var(model.Components, model.NonGlucoseUpgrading, model.Equipment, domain=NonNegativeReals)
        model.FDT14_top = Var (model.Components, model.NonGlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.FDT14_bottom = Var (model.Components, model.NonGlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.WaterStreamBiodiesel = Var (model.Components, model.NonGlucoseUpgrading,  within=NonNegativeReals)
        model.FWasher = Var (model.Components, model.NonGlucoseUpgrading, model.Equipment,within=NonNegativeReals)
        model.FWasher_top = Var (model.Components, model.NonGlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.FWasher_bottom = Var (model.Components, model.NonGlucoseUpgrading, model.Equipment,within=NonNegativeReals)
        model.FDT15_bottom = Var (model.Components, model.NonGlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.Biodiesel_product = Var (model.Components, model.NonGlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.H3PO4Stream = Var (model.Components, model.NonGlucoseUpgrading, model.Equipment,  within=NonNegativeReals)
        model.FNeutralizer = Var (model.Components, model.NonGlucoseUpgrading, model.Equipment,  within=NonNegativeReals)
        model.InitialMolesNeutralizer= Var(model.Components, model.NonGlucoseUpgrading, model.Equipment,domain=NonNegativeReals)
        model.MolesReactedNeutralizer = Var(model.Components, model.NonGlucoseUpgrading, model.Equipment, domain=NonNegativeReals)
        model.FinalMolesNeutralizer = Var(model.Components, model.NonGlucoseUpgrading, model.Equipment, domain=NonNegativeReals)
        model.FinalMassNeutralizer = Var(model.Components, model.NonGlucoseUpgrading, model.Equipment,domain=NonNegativeReals)
        model.FCentrifugal3_Liquid = Var (model.Components, model.NonGlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.FCentrifugal3_Solid = Var (model.Components, model.NonGlucoseUpgrading, model.Equipment,within=NonNegativeReals)
        model.FDT16_top = Var (model.Components, model.NonGlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.Glycerol_coproduct= Var (model.Components, model.NonGlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.totalwaste_biodiesel= Var (model.Components, model.NonGlucoseUpgrading, within=NonNegativeReals)
        #Protein extraction 
        model.ChemicalConsumptionProtein = Var (model.Components, model.NonGlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.FProtein = Var (model.Components, model.NonGlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.FCentrifugal4_Solid= Var (model.Components, model.NonGlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.FCentrifugal4_Liquid =Var (model.Components, model.NonGlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.FFiltration_Waste = Var (model.Components, model.NonGlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.ProteinProduct = Var (model.Components, model.NonGlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        #Composting
        model.Compost_product = Var(within=NonNegativeReals)
        #Incineration
        model.Ffuel = Var (model.Macronutrients, model.FWManagementOption, within=NonNegativeReals) 
        model.FBurner = Var (model.Components, model.FWManagementOption, model.Equipment, within=NonNegativeReals)
        model.InitialMolesBurner = Var (model.Components, model.FWManagementOption, model.Equipment, within=NonNegativeReals)
        model.MolesReacted1Burner = Var (model.Components, model.FWManagementOption, model.Equipment, within=NonNegativeReals)
        model.MolesReacted2Burner = Var (model.Components, model.FWManagementOption, model.Equipment, within=NonNegativeReals)
        model.MolesReacted3Burner = Var (model.Components, model.FWManagementOption, model.Equipment, within=NonNegativeReals)
        model.FinalMolesBurner = Var (model.Components, model.FWManagementOption, model.Equipment, within=NonNegativeReals)
        model.FinalMassBurner = Var (model.Components, model.FWManagementOption, model.Equipment, within=NonNegativeReals)
        model.FComp4 = Var (model.Components, model.FWManagementOption, model.Equipment, within=NonNegativeReals)
        model.FCooler = Var (model.Components, model.FWManagementOption, model.Equipment, within=NonNegativeReals)
        model.Fluegas = Var (model.Components, model.FWManagementOption, model.Equipment, within=NonNegativeReals)
        model.Ash = Var (model.Components, model.FWManagementOption, model.Equipment, within=NonNegativeReals)
        model.HeatGenerated = Var ( within=NonNegativeReals)
        model.ElectricityGenerated = Var ( within=NonNegativeReals)
        #Anaerobic digestion
        model.FAD = Var(model.Components, model.FWManagementOption, model.Equipment, within=NonNegativeReals)
        model.FWaste = Var(model.Components, model.FWManagementOption, model.Equipment, within=NonNegativeReals)
        model.FWaterWaste = Var(model.Components, model.FWManagementOption, model.Equipment, within=NonNegativeReals)
        model.InitialMolesDigester= Var(model.Components, model.FWManagementOption, model.Equipment,within=NonNegativeReals)
        model.MolesReactedDigester1 = Var(model.Components, model.FWManagementOption, model.Equipment, within=NonNegativeReals)
        model.MolesReactedDigester2 = Var(model.Components, model.FWManagementOption, model.Equipment, within=NonNegativeReals)
        model.MolesReactedDigester3 = Var(model.Components, model.FWManagementOption, model.Equipment, within=NonNegativeReals)
        model.MolesReactedDigester4 = Var(model.Components, model.FWManagementOption, model.Equipment, within=NonNegativeReals)
        model.FinalMolesDigester = Var(model.Components, model.FWManagementOption, model.Equipment, within=NonNegativeReals)
        model.FinalMassDigester = Var(model.Components, model.FWManagementOption, model.Equipment, within=NonNegativeReals)
        model.Fflashdrum5_liquid = Var (model.Components, model.FWManagementOption, model.Equipment,  within=NonNegativeReals)
        model.Fflashdrum5_gas = Var (model.Components, model.FWManagementOption, model.Equipment,  within=NonNegativeReals)
        model.FCentrifugal5_solid = Var (model.Components, model.FWManagementOption, model.Equipment, within=NonNegativeReals)
        model.FCentrifugal5_liquid = Var (model.Components, model.FWManagementOption, model.Equipment, within=NonNegativeReals)
        model.Fertilizer_coproduct = Var (model.Components, model.FWManagementOption, model.Equipment, within=NonNegativeReals)
        model.FinStage1 = Var (model.Components, model.FWManagementOption, model.Equipment, within=NonNegativeReals)
        model.FoutStage1_CO2 = Var (model.Components, model.FWManagementOption, model.Equipment, within=NonNegativeReals)
        model.FoutStage1_top = Var (model.Components, model.FWManagementOption, model.Equipment, within=NonNegativeReals)
        model.FoutStage2_CO2 = Var (model.Components, model.FWManagementOption, model.Equipment, within=NonNegativeReals)
        model.BioCNG_product= Var (model.Components, model.FWManagementOption, within=NonNegativeReals)
        #Carbon Capture
        model.FCCU1 = Var(model.Components, model.CarbonCapture, model.Equipment, within=NonNegativeReals)
        model.FinAbsorber2 = Var (model.Components, model.CarbonCapture, model.Equipment, within=NonNegativeReals)
        model.FoutAbsorber2_bottom = Var (model.Components, model.CarbonCapture, model.Equipment, within=NonNegativeReals)
        model.FoutAbsorber2_top = Var (model.Components, model.CarbonCapture, model.Equipment,within=NonNegativeReals)
        model.ChemicalSolventCCU = Var (model.Components, model.CarbonCapture, model.Equipment, within=NonNegativeReals)
        model.Finhe2= Var (model.Components, model.CarbonCapture, model.Equipment, within=NonNegativeReals)
        model.FinDT18 = Var (model.Components, model.CarbonCapture, model.Equipment, within=NonNegativeReals)
        model.FoutDT18_CO2 = Var (model.Components, model.CarbonCapture, model.Equipment, within=NonNegativeReals)
        model.FoutDT18_liquid = Var (model.Components, model.CarbonCapture, model.Equipment, within=NonNegativeReals)
        model.FinCCU2 = Var(model.Components, model.CarbonCapture, model.Equipment,within=NonNegativeReals)
        model.Solvent_recycle = Var (model.Components,model.CarbonCapture, within=NonNegativeReals)
        model.total_chemical_absorber2_needed = Var(model.Components, model.CarbonCapture, within=NonNegativeReals)
        model.fresh_water_absorber2_needed = Var(model.Components, model.CarbonCapture, within=NonNegativeReals)
        model.CO2_compression = Var (model.Components, model.CarbonCapture, model.Equipment, within=NonNegativeReals)
        #Products & co-products
        model.TotalBioethanol = Var (within=NonNegativeReals)
        model.TotalLA = Var (within=NonNegativeReals)
        model.TotalSA = Var (within=NonNegativeReals)
        model.TotalBDO = Var (within=NonNegativeReals)
        model.TotalButanol = Var (within=NonNegativeReals)
        model.TotalAcetoneCoproduct = Var (within=NonNegativeReals)
        model.TotalH2Coproduct = Var (within=NonNegativeReals)
        model.EthanolCoproduct = Var (within=NonNegativeReals)
        model.TotalBiodiesel = Var (within=NonNegativeReals)
        model.TotalGlycerol =Var (within=NonNegativeReals)
        model.TotalProtein = Var (within=NonNegativeReals)
        model.TotalBioCNG = Var (within=NonNegativeReals)
        model.TotalFertilizer = Var (within=NonNegativeReals)
        model.TotalCO2 = Var (within=NonNegativeReals)
        model.GateFeeComposting = Var (within=NonNegativeReals)
        model.GateFeeIncineration = Var (within=NonNegativeReals)
        model.GateFeeAD = Var (within=NonNegativeReals)
        model.GGSS_biomethane = Var (within=NonNegativeReals)
        #Waste recovery 
        model.Organicwaste = Var (within=NonNegativeReals)
        model.SolidWaste = Var (within=NonNegativeReals)
        model.FlueGasStream = Var (within=NonNegativeReals)
        model.OffgasStream = Var (within=NonNegativeReals)
        model.Total_OffgasStream = Var (within=NonNegativeReals)

        #Capital investment 
        model.crusher_equipment_cost = Var(model.Milling, model.Equipment, within=NonNegativeReals)
        model.pretreatment_equipment_cost = Var(model.FWManagementOption, model.Equipment, within=NonNegativeReals)
        model.bioethanol_equipment_cost = Var(model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.Lactic_equipment_cost = Var (model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.Succinic_equipment_cost = Var (model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.BDO_equipment_cost = Var (model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.Butanol_equipment_cost = Var(model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.Biodiesel_equipment_cost = Var(model.NonGlucoseUpgrading, model.Equipment, within=NonNegativeReals) 
        model.Protein_equipment_cost = Var (model.NonGlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.Incineration_equipment_cost = Var (model.FWManagementOption, model.Equipment, within=NonNegativeReals)
        model.AD_equipment_cost = Var (model.FWManagementOption, model.Equipment,   within=NonNegativeReals)
        model.CCU_equipment_cost = Var (model.CarbonCapture, model.Equipment,   within=NonNegativeReals)
        model.Equipment_total_cost = Var(within=NonNegativeReals)
        model.CapitalInvestmentComposting = Var(within=NonNegativeReals)
        model.total_plant_direct_cost = Var(within=NonNegativeReals)
        model.total_plant_indirect_cost = Var(within=NonNegativeReals)
        model.total_plant_cost = Var(within=NonNegativeReals)
        model.fixed_capital_investment = Var(within=NonNegativeReals)
        model.total_capital_investment = Var(within=NonNegativeReals)
        #Operating cost 
        #Electricity
        model.Utin_electricity_grinding = Var(model.Utility, model.Milling, model.Equipment, within=NonNegativeReals)
        model.Utin_electricity_EnzymaticHydrolysis = Var(model.Utility,model.FWManagementOption, model.Equipment, within=NonNegativeReals)
        model.Utin_electricity_BioethanolProcess= Var(model.Utility,model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.Utin_electricity_LacticProcess= Var(model.Utility,model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.Utin_electricity_SuccinicProcess= Var(model.Utility,model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.Utin_electricity_BDOProcess= Var(model.Utility,model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.Utin_electricity_ButanolProcess= Var(model.Utility,model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.Utin_electricity_BiodieselProcess= Var(model.Utility,model.NonGlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.Utin_electricity_Protein= Var(model.Utility,model.NonGlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.Utin_electricity_Incineration= Var(model.Utility, model.FWManagementOption, model.Equipment, within=NonNegativeReals)
        model.Utin_electricity_AD= Var(model.Utility,model.FWManagementOption, model.Equipment, within=NonNegativeReals)
        model.Utin_electricity_CCU= Var(model.Utility, model.CarbonCapture, model.Equipment, within=NonNegativeReals)
        model.Utin_electricity_Composting= Var(model.Utility, model.FWManagementOption, within=NonNegativeReals)
        model.Utin_electricity_total_consumption= Var(model.Utility,within=NonNegativeReals)
        model.electricity_cost = Var(within=NonNegativeReals)
        #model.electricity_excess = Var (within=NonNegativeReals)
        #Heat
        model.Utin_heat_EnzymaticHydrolysis = Var(model.Utility,model.FWManagementOption, model.Equipment, within=NonNegativeReals)
        model.Utin_heat_Bioethanol = Var(model.Utility,model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.Utin_heat_Lactic = Var(model.Utility,model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.Utin_heat_Succinic = Var(model.Utility,model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.Utin_heat_BDO = Var(model.Utility,model.GlucoseUpgrading,  model.Equipment, within=NonNegativeReals)
        model.Utin_heat_Butanol = Var(model.Utility,model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.Utin_heat_Biodiesel = Var(model.Utility,model.NonGlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.Utin_heat_CCU= Var(model.Utility,model.CarbonCapture, model.Equipment, within=NonNegativeReals)
        model.Utin_heat_Composting = Var(model.Utility,model.FWManagementOption, within=NonNegativeReals)
        model.Utin_heat_Incineration = Var(model.Utility,model.FWManagementOption, model.Equipment, within=NonNegativeReals)
        model.Utin_heat_total_consumption= Var(model.Utility, within=NonNegativeReals)
        model.heat_cost = Var(within=NonNegativeReals)

        #Cooling water
        model.Utin_coolingwater_EnzymaticHydrolysis = Var(model.Utility, model.FWManagementOption, model.Equipment, within=NonNegativeReals)
        model.Utin_coolingwater_Bioethanol = Var(model.Utility, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.Utin_coolingwater_Lactic = Var(model.Utility,model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.Utin_coolingwater_Succinic = Var(model.Utility,model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.Utin_coolingwater_BDO = Var(model.Utility, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.Utin_coolingwater_Butanol = Var(model.Utility, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.Utin_coolingwater_Biodiesel = Var(model.Utility,model.NonGlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.Utin_coolingwater_CCU= Var(model.Utility,model.CarbonCapture, model.Equipment, within=NonNegativeReals)
        model.Utin_coolingwater_Incineration = Var(model.Utility, model.FWManagementOption, model.Equipment, within=NonNegativeReals)       
        model.Utin_coolingwater_total_consumption= Var(model.Utility, within=NonNegativeReals)
        model.cooling_water_cost = Var(within=NonNegativeReals)
        #Chilling
        model.Utin_chilling_Succinic = Var(model.Utility, within=NonNegativeReals)
        #Utility cost
        model.total_utility_cost= Var(within=NonNegativeReals)
        #Raw material and chemical cost
        model.total_collection_cost = Var(within=NonNegativeReals)
        model.total_sorting_cost = Var(within=NonNegativeReals)
        model.total_other_cost = Var(within=NonNegativeReals)
        model.FWConsumption = Var (within=NonNegativeReals)
        model.FW_cost= Var( model.Milling, model.Equipment, within=NonNegativeReals)
        model.Chemical_pretreatment_consumption = Var(model.Chemicals, model.FWManagementOption, model.Equipment, within=NonNegativeReals)
        model.Chemical_cost_pretreatment = Var(within=NonNegativeReals)
        model.Total_Chemical_Bioethanol_Consumption = Var(model.Chemicals, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.Chemical_cost_Bioethanol = Var (within=NonNegativeReals)
        model.Total_Chemical_Lactic_Consumption = Var(model.Chemicals, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.Chemical_cost_Lactic = Var (within=NonNegativeReals)
        model.Total_Chemical_Succinic_Consumption = Var(model.Chemicals, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.Chemical_cost_Succinic = Var (within=NonNegativeReals)
        model.Total_Chemical_BDO_Consumption = Var(model.Chemicals, model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.Chemical_cost_BDO = Var (within=NonNegativeReals)
        model.Total_Chemical_Butanol_Consumption = Var(model.Chemicals,model.GlucoseUpgrading, model.Equipment, within=NonNegativeReals)
        model.Chemical_cost_Butanol = Var (within=NonNegativeReals)
        model.Chemical_Biodiesel_Consumption = Var(model.Components, model.NonGlucoseUpgrading, within=NonNegativeReals)
        model.Chemical_cost_Biodiesel = Var(within=NonNegativeReals)
        model.Chemical_Protein_Consumption = Var(model.Components, model.NonGlucoseUpgrading,within=NonNegativeReals)
        model.Chemical_cost_Protein = Var(within=NonNegativeReals)
        model.Chemical_composting_Consumption = Var (model.Components,  model.FWManagementOption, within=NonNegativeReals)
        model.Chemical_cost_Composting = Var (within=NonNegativeReals)
        model.total_raw_material_cost= Var(within=NonNegativeReals)
        #Operational cost 
        model.cost_of_manufacturing = Var(within=NonNegativeReals)
        model.operating_labor = Var(within=NonNegativeReals)
        model.supervisory_clerical_labor = Var(within=NonNegativeReals)
        model.maintenance_repair = Var(within=NonNegativeReals)
        model.operating_supplies= Var(within=NonNegativeReals)
        model.laboratory_charges = Var(within=NonNegativeReals)
        model.patents_royalties  = Var(within=NonNegativeReals)
        model.direct_manufacturing_cost = Var(within=NonNegativeReals)
        model.local_taxes_insurance= Var(within=NonNegativeReals)
        model.plant_overhead = Var(within=NonNegativeReals)
        model.fixed_manufacturing_cost = Var(within=NonNegativeReals)
        model.administration_cost = Var(within=NonNegativeReals)
        model.distribution_selling_cost= Var(within=NonNegativeReals)
        model.research_development_cost = Var(within=NonNegativeReals)
        model.general_manufacturing_cost = Var(within=NonNegativeReals)
        model.total_operating_cost = Var(within=NonNegativeReals)
        #Profitability analysis
        model.total_product_revenue = Var (within=NonNegativeReals) 
        model.profit = Var(within=Reals)
        model.large_number = Param(initialize=1e12)
        model.small_number = Param(initialize=1e-6)
        model.npv = Var(within=Reals)
        model.discounted_cash_flow = Var(model.ConstructionYears.union(model.OperationalYears), within=Reals)
        investment_distribution = {1: 0.08, 2: 0.32, 3: 0.60}
        model.investment_percentage = Param(RangeSet(1, 3), initialize=investment_distribution, within=NonNegativeReals)
        model.net_cash_flow = Var(model.ConstructionYears.union(model.OperationalYears), within=Reals)
        model.depreciation = Var(model.OperationalYears , within=NonNegativeReals)
        model.gross_profit = Var(model.OperationalYears , within=Reals)
        model.profit_before_tax = Var(model.OperationalYears , within=Reals)
        model.income_tax = Var(model.OperationalYears , within=Reals)
        model.net_profit = Var(model.OperationalYears , within=Reals)
        model.tax_indicator = Var(model.OperationalYears, within=Binary)
        #GWP
        model.GWPelectricity = Var (within=NonNegativeReals)
        model.GWPcoolingwater = Var(within=NonNegativeReals)
        model.GWPheat = Var(within=NonNegativeReals)
        model.GWPchilling = Var(within=NonNegativeReals)
        model.GWPchemicalLCA = Var (within=NonNegativeReals)
        model.GWPEmissionDirect =  Var (within=NonNegativeReals)
        model.GWPcredit = Var (within=NonNegativeReals)
        model.GWPSavings = Var (within=Reals)
        # === Job Generation ===
        model.JobGeneration = Var(model.SocialImpact, within=Reals)
        model.SIA = Var(within=Reals)